#!/usr/bin/env bash
# script that transfers a file from our client to a server


# Check if the number of parameters is less than 4
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
ip="$2"
usrname="$3"
ssh_key="$4"

# Transfer the file to the user's home directory on the server
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip":~/

# Check if the scp command was successful
if [ $? -eq 0 ]; then
    echo "File $file_path transferred successfully to $username@$server_ip:~/"
else
    echo "Error: File transfer failed."
fi

