#!/usr/bin/env bash
# script that transfers a file from our client to a server

# Check if the number of arguments is less than 3
if [ $# -lt 3 ]; then
    echo "Usage: $0 file_path ip usrname [ssh_key]"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
ip="$2"
usrname="$3"
ssh_key="$4"

# Use a default SSH key if not provided
if [ -z "$ssh_key" ]; then
    ssh_key="~/.ssh/id_rsa"
fi

# Transfer the file using scp
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$usrname"@"$ip":~/
