#!/usr/bin/env bash
# Install nginx web server

# Update the package list
apt-get update

# Install Nginx
apt-get -y install nginx

# Create an index.html file with the content "Hello World!"
mkdir /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

# Start Nginx (without using systemctl)
service nginx start
