#!/usr/bin/env bash
# Install nginx web server

# Update the package list
apt-get update

# Install Nginx
apt-get -y install nginx

# Create an index.html file with the content "Hello World!"
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Start Nginx (without using systemctl)
service nginx start
