#!/usr/bin/env bash

# Install nginx web server


# Update package lists and install nginx
apt-get -y update
apt-get -y install nginx

# Create a simple HTML file with "Hello World!"
mkdir --parents /var/www/html
echo 'Hello World' > /var/www/html/index.html
service nginx restart
