#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header

url_1="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
url2="server {\n\tadd_header X-Served-By $(hostname);"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" > /usr/share/nginx/html/index.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$url_1/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$url_2/" /etc/nginx/sites-available/default
sudo service nginx start
