#!/usr/bin/env bash
# Sets the key and file nmame
key_name="school"
passphrase="betty
ssh-keygen -t rsa -b 4096 -f "$key_name" -N "$passphrase"

echo "Generating public/private rsa key pair"
echo "Your identification has been saved in $key_name"
echo "Your public key has been saved in ${key_name}.pub"
ssh-keygen -l -f '$key_name'
